services:

  # roda na porta 6379
  servicos_redis:
    container_name: servicos_redis
    restart: always
    image: redis:6.0-alpine3.16
    volumes:
      - servicos_redis_data:/data
    networks:
      - servicos_network
    command: redis-server --appendonly yes
    env_file:
      - .env
    ports:
      - 6379:6379

  # roda nas portas 5672 e 15672
  servicos_rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: servicos_rabbitmq
    hostname: servicos_rabbitmq
    restart: always
    volumes:
        - servicos_rabbitmq_data:/var/lib/rabbitmq/
        - ./backups:/backups
    networks:
      - servicos_network
    env_file:
      - .env
    ports:
        - 15672:15672
        - 5672:5672

  # roda na porta 5432
  servicos_postgres:
    container_name: servicos_postgres
    restart: always
    image: postgres:16.1-bullseye
    shm_size: 1gb
    volumes:
      - servicos_postgres_data:/var/lib/postgresql/data/
      - ./backups:/backups
    networks:
      - servicos_network
    env_file:
      - .env
    ports:
      - 5432:5432

  # roda na porta 6432
  # servicos_pgbouncer:
  #   container_name: servicos_pgbouncer
  #   restart: always
  #   image: bitnami/pgbouncer:latest
  #   networks:
  #     - servicos_network
  #   env_file:
  #     - .env
  #   ports:
  #     - 6432:6432


volumes:
  servicos_postgres_data:
    name: servicos_postgres_data
  servicos_redis_data:
    name: servicos_redis_data
  servicos_rabbitmq_data:
    name: servicos_rabbitmq_data

networks:
  servicos_network:
    external: true
